# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db25eb81307658cf395965edbcfd626671e01c304b78d8246a75abb6cb970f221cedaa6a7c2f6d06af5762bcb322bcf6bc726c5209332ab9a3a2cc8ff3159038

test:
  secret_key_base: 4f31508a0fcf2ae4c5a5dc040f756a3e20f538638cf25199100490ad2bb93afe035dd91bd0ea8f04567b7f988770b5f79ed90fd849523567d12155a5ba6f8e8f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
